language: python
python:
  - '3.6'

before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip install pep8
    
script:
  - pep8 --ignore=E501 ./package_name
